from qgis.core import *
from qgis.gui import *
import re

@qgsfunction(args='auto', group='Custom')
def format_place_name(name, population, name_pref_suf_lang, feature, parent):
    n = name

    if "name" == n.lower(): n = ""
    if "name ?" == n.lower(): n = ""
    if "санатория" in n.lower(): n = re.sub("санатория","сан.", n, flags=re.IGNORECASE)
    if "санаторий" in n.lower(): n = re.sub("санаторий","сан.", n, flags=re.IGNORECASE)
    if "лесничества" in n.lower(): n = re.sub("лесничества","леснич.", n, flags=re.IGNORECASE)
    if "лесничество" in n.lower(): n = re.sub("лесничество","леснич.", n, flags=re.IGNORECASE)
    if "кордон " in n.lower(): n = re.sub("кордон ","корд. ", n, flags=re.IGNORECASE)
    if " кордон" in n.lower(): n = re.sub(" кордон"," корд.", n, flags=re.IGNORECASE)
    if "участок" in n.lower(): n = re.sub("участок","уч.", n, flags=re.IGNORECASE)
    if "участка" in n.lower(): n = re.sub("участка","уч.", n, flags=re.IGNORECASE)
    if "имени" in n.lower(): n = re.sub("имени","им.", n, flags=re.IGNORECASE)
    if "торфопредприятия" in n.lower(): n = re.sub("торфопредприятия","торф.", n, flags=re.IGNORECASE)
    if "торфопредприятие" in n.lower(): n = re.sub("торфопредприятие","торф.", n, flags=re.IGNORECASE)
    if "рыбопитомника" in n.lower(): n = re.sub("рыбопитомника","рыб.", n, flags=re.IGNORECASE)
    if "рыбопитомник" in n.lower(): n = re.sub("рыбопитомник","рыб.", n, flags=re.IGNORECASE)
    if " питомник" in n.lower(): n = re.sub(" питомник"," пит.", n, flags=re.IGNORECASE)
    if "охотхозяйство" in n.lower(): n = re.sub("охотхозяйство","охот.", n, flags=re.IGNORECASE)
    if "охотхозяйства" in n.lower(): n = re.sub("охотхозяйства","охот.", n, flags=re.IGNORECASE)
    if "хозяйство" in n.lower(): n = re.sub("хозяйство","хоз-во", n, flags=re.IGNORECASE)
    if "микрорайона" in n.lower(): n = re.sub("микрорайона","мкр.", n, flags=re.IGNORECASE)
    if "микрорайон" in n.lower(): n = re.sub("микрорайон","мкр.", n, flags=re.IGNORECASE)
    if "район" in n.lower(): n = re.sub("район","р-н", n, flags=re.IGNORECASE)
    if " станция" in n.lower(): n = re.sub(" станция"," ст.", n, flags=re.IGNORECASE)
    if n.lower().startswith('станция '): n = re.sub("^станция ","ст. ", n, flags=re.IGNORECASE)
    if "полуостров" in n.lower() and " " in n: n = re.sub("полуостров","п-ов.", n, flags=re.IGNORECASE)
    if "пристань" in n.lower(): n = re.sub("пристань","прист.", n, flags=re.IGNORECASE)
    if n.lower().startswith('поселок'): n = re.sub("^поселок","пос.", n, flags=re.IGNORECASE)
    if n.lower().startswith('посёлок'): n = re.sub("^посёлок","пос.", n, flags=re.IGNORECASE)
    if n.lower().startswith('рабочий поселок'): n = re.sub("^рабочий поселок","раб. пос.", n, flags=re.IGNORECASE)
    if n.lower().startswith('рабочий посёлок'): n = re.sub("^рабочий посёлок","раб. пос.", n, flags=re.IGNORECASE)
    if n.lower().startswith('дом отдыха'): n = re.sub("^дом отдыха","д.о.", n, flags=re.IGNORECASE)
    if "база отдыха" in n.lower(): n = re.sub("база отдыха","б.о.", n, flags=re.IGNORECASE)
    if "турбаза" in n.lower(): n = re.sub("турбаза","т/б", n, flags=re.IGNORECASE)
    if "турбазы" in n.lower(): n = re.sub("турбазы","т/б", n, flags=re.IGNORECASE)
    if "пионерлагерь" in n.lower(): n = re.sub("пионерлагерь","пионерлаг.", n, flags=re.IGNORECASE)
    if "альплагерь" in n.lower(): n = re.sub("альплагерь","а/л", n, flags=re.IGNORECASE)
    if "садоводческое товарищество" in n.lower(): n = re.sub("садоводческое товарищество","СТ", n, flags=re.IGNORECASE)
    if "коттеджный поселок" in n.lower(): n = re.sub("коттеджный поселок","КП", n, flags=re.IGNORECASE)
    if "коттеджный посёлок" in n.lower(): n = re.sub("коттеджный посёлок","КП", n, flags=re.IGNORECASE)
    if n.lower().startswith('урочище '): n = re.sub("^урочище ","ур.", n, flags=re.IGNORECASE)
    if n.lower().endswith(' урочище'): n = re.sub(" урочище$","ур.", n, flags=re.IGNORECASE)
    if n.lower().startswith('урочища '): n = re.sub("^урочища ","ур.", n, flags=re.IGNORECASE)
    if n.lower().endswith(' урочища'): n = re.sub(" урочища$","ур.", n, flags=re.IGNORECASE)
    if " урочища " in n.lower(): n = re.sub(" урочища "," ур. ", n, flags=re.IGNORECASE)
    if n.lower().startswith('долина'): n = re.sub("^долина","дол.", n, flags=re.IGNORECASE)
    if n.lower().endswith('долина'): n = re.sub("долина$","дол.", n, flags=re.IGNORECASE)
    if n.lower().startswith('поляна'): n = re.sub("^поляна","пол.", n, flags=re.IGNORECASE)
    if n.lower().endswith('поляна'): n = re.sub("поляна$","пол.", n, flags=re.IGNORECASE)
    if n.lower().startswith('ущелье'): n = re.sub("^ущелье","ущ.", n, flags=re.IGNORECASE)
    if n.lower().endswith('ущелье'): n = re.sub("ущелье$","ущ.", n, flags=re.IGNORECASE)
    if "застава" in n.lower(): n = re.sub("застава","заст.", n, flags=re.IGNORECASE)
    if "озеро" in n.lower() and " " in n: n = re.sub("озеро","оз.", n, flags=re.IGNORECASE)
    if n.lower().startswith('острова '): n = re.sub("^острова ","о-ва ", n, flags=re.IGNORECASE)
    if n.lower().endswith(' острова'): n = re.sub(" острова$"," о-ва", n, flags=re.IGNORECASE)
    if " острова " in n.lower(): n = re.sub(" острова "," о-ва ", n, flags=re.IGNORECASE)
    if "остров " in n.lower() and " " in n and "ур." not in n.lower() and "островн" not in n.lower() and "Острова" not in n: n = re.sub("остров ","о. ", n, flags=re.IGNORECASE)
    if " остров" in n.lower() and " " in n and "ур." not in n.lower() and "островн" not in n.lower() and "Острова" not in n: n = re.sub(" остров"," о.", n, flags=re.IGNORECASE)
    if "болото" in n.lower() and " " in n: n = re.sub("болото","бол.", n, flags=re.IGNORECASE)
    if "зимник" in n.lower(): n = re.sub("зимник","зим.", n, flags=re.IGNORECASE)
    if n.lower().startswith('зимовка '): n = re.sub("^зимовка ","зим. ", n, flags=re.IGNORECASE)
    if n.lower().endswith(' зимовка'): n = re.sub(" зимовка$"," зим.", n, flags=re.IGNORECASE)
    if n.lower().startswith('летник') and "летники" not in n.lower(): n = re.sub("летник","лет.", n, flags=re.IGNORECASE)
    if "балка " in n.lower(): n = re.sub("балка ","б. ", n, flags=re.IGNORECASE)
    if " балка" in n.lower(): n = re.sub(" балка"," б.", n, flags=re.IGNORECASE)
    if "овраг " in n.lower(): n = re.sub("овраг ","овр. ", n, flags=re.IGNORECASE)
    if " овраг" in n.lower(): n = re.sub(" овраг"," овр.", n, flags=re.IGNORECASE)
    if "монастырь " in n.lower(): n = re.sub("монастырь ","мон.", n, flags=re.IGNORECASE)
    if " монастырь" in n.lower(): n = re.sub(" монастырь"," мон.", n, flags=re.IGNORECASE)
    if "женский" in n.lower(): n = re.sub("женский","жен.", n, flags=re.IGNORECASE)
    if "женская" in n.lower(): n = re.sub("женская","жен.", n, flags=re.IGNORECASE)
    if "мужской" in n.lower(): n = re.sub("мужской","муж.", n, flags=re.IGNORECASE)
    if "мужская" in n.lower(): n = re.sub("мужская","муж.", n, flags=re.IGNORECASE)
    if "святой" in n.lower() and " " in n: n = re.sub("святой","св.", n, flags=re.IGNORECASE)
    if "святого" in n.lower() and " " in n: n = re.sub("святого","св.", n, flags=re.IGNORECASE)

    if n.lower().startswith('большой') and " " in n: n = re.sub("большой","Бол.", n, flags=re.IGNORECASE)
    if n.lower().startswith('большие') and " " in n: n = re.sub("большие","Бол.", n, flags=re.IGNORECASE)
    if n.lower().startswith('большая') and " " in n: n = re.sub("большая","Бол.", n, flags=re.IGNORECASE)
    elif "верхняя" in n.lower() and " " in n: n = re.sub("верхняя","Верх.", n, flags=re.IGNORECASE)
    elif "верхний" in n.lower() and " " in n: n = re.sub("верхний","Верх.", n, flags=re.IGNORECASE)
    elif "верхние" in n.lower() and " " in n: n = re.sub("верхние","Верх.", n, flags=re.IGNORECASE)
    elif "верхнее" in n.lower() and " " in n: n = re.sub("верхнее","Верх.", n, flags=re.IGNORECASE)
    elif "средняя" in n.lower() and " " in n: n = re.sub("средняя","Средн.", n, flags=re.IGNORECASE)
    elif "средний" in n.lower() and " " in n: n = re.sub("средний","Средн.", n, flags=re.IGNORECASE)
    elif "средние" in n.lower() and " " in n: n = re.sub("средние","Средн.", n, flags=re.IGNORECASE)
    elif "среднее" in n.lower() and " " in n: n = re.sub("среднее","Средн.", n, flags=re.IGNORECASE)
    elif "большое" in n.lower() and " " in n and 'торф' not in n and 'ебольшое' not in n: n = re.sub("большое","Бол.", n, flags=re.IGNORECASE)
    elif "красная" in n.lower() and " " in n: n = re.sub("красная","Кр.", n, flags=re.IGNORECASE)
    elif "красный" in n.lower() and " " in n: n = re.sub("красный","Кр.", n, flags=re.IGNORECASE)
    elif "красные" in n.lower() and " " in n: n = re.sub("красные","Кр.", n, flags=re.IGNORECASE)
    elif "красное" in n.lower() and " " in n: n = re.sub("красное","Кр.", n, flags=re.IGNORECASE)
    elif "старая" in n.lower() and " " in n: n = re.sub("старая","Стар.", n, flags=re.IGNORECASE)
    elif "старый" in n.lower() and " " in n: n = re.sub("старый","Стар.", n, flags=re.IGNORECASE)
    elif "старые" in n.lower() and " " in n: n = re.sub("старые","Стар.", n, flags=re.IGNORECASE)
    elif "старое" in n.lower() and " " in n: n = re.sub("старое","Стар.", n, flags=re.IGNORECASE)
    elif "нижняя" in n.lower() and " " in n: n = re.sub("нижняя","Ниж.", n, flags=re.IGNORECASE)
    elif "нижний" in n.lower() and " " in n: n = re.sub("нижний","Ниж.", n, flags=re.IGNORECASE)
    elif "нижние" in n.lower() and " " in n: n = re.sub("нижние","Ниж.", n, flags=re.IGNORECASE)
    elif "нижнее" in n.lower() and " " in n: n = re.sub("нижнее","Ниж.", n, flags=re.IGNORECASE)
    elif "малая" in n.lower() and " " in n: n = re.sub("малая","Мал.", n, flags=re.IGNORECASE)
    elif "малый" in n.lower() and " " in n: n = re.sub("малый","Мал.", n, flags=re.IGNORECASE)
    elif "малые" in n.lower() and " " in n: n = re.sub("малые","Мал.", n, flags=re.IGNORECASE)
    elif "малое" in n.lower() and " " in n: n = re.sub("малое","Мал.", n, flags=re.IGNORECASE)
    elif n.lower().startswith('новая '): n = re.sub("^новая ","Нов. ", n, flags=re.IGNORECASE)
    elif n.lower().startswith('новый '): n = re.sub("^новый ","Нов. ", n, flags=re.IGNORECASE)
    elif n.lower().startswith('новые '): n = re.sub("^новые ","Нов. ", n, flags=re.IGNORECASE)
    elif n.lower().startswith('новое '): n = re.sub("^новое ","Нов. ", n, flags=re.IGNORECASE)
    elif n.lower().endswith(' новая'): n = re.sub(" новая$"," Нов.", n, flags=re.IGNORECASE)
    elif n.lower().endswith(' новый'): n = re.sub(" новый$"," Нов.", n, flags=re.IGNORECASE)
    elif n.lower().endswith(' новые'): n = re.sub(" новые$"," Нов.", n, flags=re.IGNORECASE)
    elif n.lower().endswith(' новое'): n = re.sub(" новое$", "Нов.", n, flags=re.IGNORECASE)

    if n.lower().startswith("неизвестный"): n = re.sub("неизвестный","Неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().endswith("неизвестный"): n = re.sub("неизвестный","неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().startswith("неизвестное"): n = re.sub("неизвестное","Неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().endswith("неизвестное"): n = re.sub("неизвестное","неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().startswith("неизвестная"): n = re.sub("неизвестная","Неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().endswith("неизвестная"): n = re.sub("неизвестная","неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().startswith("неизвестные"): n = re.sub("неизвестные","Неизвестн.",n, flags=re.IGNORECASE)
    if n.lower().endswith("неизвестные"): n = re.sub("неизвестные","неизвестн.",n, flags=re.IGNORECASE)

    if n.lower().startswith("заброшенный "): n = re.sub("заброшенный ","забр. ",n, flags=re.IGNORECASE)
    if n.lower().startswith("заброшенная "): n = re.sub("заброшенная ","забр. ",n, flags=re.IGNORECASE)
    if n.lower().startswith("заброшенное "): n = re.sub("заброшенное ","забр. ",n, flags=re.IGNORECASE)
    if n.lower().startswith("заброшенные "): n = re.sub("заброшенные ","забр. ",n, flags=re.IGNORECASE)

    if "перевал " in n.lower(): n = re.sub("перевал ","пер. ", n, flags=re.IGNORECASE)

    if population == "0" and name_pref_suf_lang == "ru": n = n + "\n(неж.)"

    return n
